name = "binder_example"
uuid = "9d2e38f2-505c-469a-be94-d6458e0ae844"
authors = ["kfgarrity <kevin.garrity@nist.gov>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ThreeBodyTB = "2a26a249-28ed-4bc9-828d-d3ac47f0d73d"
