name = "binder_example"
uuid = "9d2e38f2-505c-469a-be94-d6458e0ae844"
authors = ["kfgarrity <kevin.garrity@nist.gov>"]
version = "0.1.0"

[deps]
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"

[compat]
julia = "1.7"
